scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets:
        - "node-exporter:9100"

  - job_name: hetzner_service_discovery
    hetzner_sd_configs:
      - role: "hcloud"
        bearer_token: "" # insert hetzner api token
        port: 9100
      - role: "robot"
        basic_auth:
          username: "" # insert username
          password: "" # insert password
        port: 9100